/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as UserAddressesIndexRouteImport } from './routes/user/addresses/index'
import { Route as UserChangePasswordIndexRouteImport } from './routes/user/change-password/index'
import { Route as UserOrdersIndexRouteImport } from './routes/user/orders/index'
import { Route as UserProfileIndexRouteImport } from './routes/user/profile/index'
import { Route as UserSessionsIndexRouteImport } from './routes/user/sessions/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAddressesIndexRoute = UserAddressesIndexRouteImport.update({
  id: '/user/addresses/',
  path: '/user/addresses/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserChangePasswordIndexRoute = UserChangePasswordIndexRouteImport.update({
  id: '/user/change-password/',
  path: '/user/change-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserOrdersIndexRoute = UserOrdersIndexRouteImport.update({
  id: '/user/orders/',
  path: '/user/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/user/profile/',
  path: '/user/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSessionsIndexRoute = UserSessionsIndexRouteImport.update({
  id: '/user/sessions/',
  path: '/user/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/login/': typeof LoginIndexRoute
  '/user/addresses/': typeof UserAddressesIndexRoute
  '/user/change-password/': typeof UserChangePasswordIndexRoute
  '/user/orders/': typeof UserOrdersIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/sessions/': typeof UserSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/login': typeof LoginIndexRoute
  '/user/addresses': typeof UserAddressesIndexRoute
  '/user/change-password': typeof UserChangePasswordIndexRoute
  '/user/orders': typeof UserOrdersIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
  '/user/sessions': typeof UserSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/login/': typeof LoginIndexRoute
  '/user/addresses/': typeof UserAddressesIndexRoute
  '/user/change-password/': typeof UserChangePasswordIndexRoute
  '/user/orders/': typeof UserOrdersIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/sessions/': typeof UserSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/signup'
    | '/wishlist'
    | '/categories/$slug'
    | '/products/$productId'
    | '/login/'
    | '/user/addresses/'
    | '/user/change-password/'
    | '/user/orders/'
    | '/user/profile/'
    | '/user/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/signup'
    | '/wishlist'
    | '/categories/$slug'
    | '/products/$productId'
    | '/login'
    | '/user/addresses'
    | '/user/change-password'
    | '/user/orders'
    | '/user/profile'
    | '/user/sessions'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/signup'
    | '/wishlist'
    | '/categories/$slug'
    | '/products/$productId'
    | '/login/'
    | '/user/addresses/'
    | '/user/change-password/'
    | '/user/orders/'
    | '/user/profile/'
    | '/user/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  UserAddressesIndexRoute: typeof UserAddressesIndexRoute
  UserChangePasswordIndexRoute: typeof UserChangePasswordIndexRoute
  UserOrdersIndexRoute: typeof UserOrdersIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
  UserSessionsIndexRoute: typeof UserSessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/addresses/': {
      id: '/user/addresses/'
      path: '/user/addresses'
      fullPath: '/user/addresses/'
      preLoaderRoute: typeof UserAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/change-password/': {
      id: '/user/change-password/'
      path: '/user/change-password'
      fullPath: '/user/change-password/'
      preLoaderRoute: typeof UserChangePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/orders/': {
      id: '/user/orders/'
      path: '/user/orders'
      fullPath: '/user/orders/'
      preLoaderRoute: typeof UserOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile/': {
      id: '/user/profile/'
      path: '/user/profile'
      fullPath: '/user/profile/'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/sessions/': {
      id: '/user/sessions/'
      path: '/user/sessions'
      fullPath: '/user/sessions/'
      preLoaderRoute: typeof UserSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  UserAddressesIndexRoute: UserAddressesIndexRoute,
  UserChangePasswordIndexRoute: UserChangePasswordIndexRoute,
  UserOrdersIndexRoute: UserOrdersIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
  UserSessionsIndexRoute: UserSessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
