/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedCartRouteImport } from './routes/_protected/cart'
import { Route as ProtectedWishlistRouteImport } from './routes/_protected/wishlist'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/_auth/forgot-password'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/_auth/reset-password'
import { Route as PublicAuthSignupRouteImport } from './routes/_public/_auth/signup'
import { Route as PublicAuthVerifyEmailRouteImport } from './routes/_public/_auth/verify-email'
import { Route as PublicCategoriesIndexRouteImport } from './routes/_public/categories/index'
import { Route as PublicProductsIndexRouteImport } from './routes/_public/products/index'
import { Route as PublicProductsProductIdRouteImport } from './routes/_public/products/$productId'
import { Route as ProtectedUserAddressesIndexRouteImport } from './routes/_protected/user/addresses/index'
import { Route as ProtectedUserChangePasswordIndexRouteImport } from './routes/_protected/user/change-password/index'
import { Route as ProtectedUserOrdersIndexRouteImport } from './routes/_protected/user/orders/index'
import { Route as ProtectedUserProfileIndexRouteImport } from './routes/_protected/user/profile/index'
import { Route as ProtectedUserSessionsIndexRouteImport } from './routes/_protected/user/sessions/index'
import { Route as PublicProductsDealsIndexRouteImport } from './routes/_public/products/deals/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCartRoute = ProtectedCartRouteImport.update({
  id: '/_protected/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWishlistRoute = ProtectedWishlistRouteImport.update({
  id: '/_protected/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/_public/_auth/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/_public/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/_public/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthSignupRoute = PublicAuthSignupRouteImport.update({
  id: '/_public/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthVerifyEmailRoute = PublicAuthVerifyEmailRouteImport.update({
  id: '/_public/_auth/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCategoriesIndexRoute = PublicCategoriesIndexRouteImport.update({
  id: '/_public/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/_public/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProductsProductIdRoute = PublicProductsProductIdRouteImport.update({
  id: '/_public/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUserAddressesIndexRoute =
  ProtectedUserAddressesIndexRouteImport.update({
    id: '/_protected/user/addresses/',
    path: '/user/addresses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedUserChangePasswordIndexRoute =
  ProtectedUserChangePasswordIndexRouteImport.update({
    id: '/_protected/user/change-password/',
    path: '/user/change-password/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedUserOrdersIndexRoute =
  ProtectedUserOrdersIndexRouteImport.update({
    id: '/_protected/user/orders/',
    path: '/user/orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedUserProfileIndexRoute =
  ProtectedUserProfileIndexRouteImport.update({
    id: '/_protected/user/profile/',
    path: '/user/profile/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedUserSessionsIndexRoute =
  ProtectedUserSessionsIndexRouteImport.update({
    id: '/_protected/user/sessions/',
    path: '/user/sessions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicProductsDealsIndexRoute =
  PublicProductsDealsIndexRouteImport.update({
    id: '/_public/products/deals/',
    path: '/products/deals/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof ProtectedCartRoute
  '/wishlist': typeof ProtectedWishlistRoute
  '/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/reset-password': typeof PublicAuthResetPasswordRoute
  '/signup': typeof PublicAuthSignupRoute
  '/verify-email': typeof PublicAuthVerifyEmailRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/categories/': typeof PublicCategoriesIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/user/addresses/': typeof ProtectedUserAddressesIndexRoute
  '/user/change-password/': typeof ProtectedUserChangePasswordIndexRoute
  '/user/orders/': typeof ProtectedUserOrdersIndexRoute
  '/user/profile/': typeof ProtectedUserProfileIndexRoute
  '/user/sessions/': typeof ProtectedUserSessionsIndexRoute
  '/products/deals/': typeof PublicProductsDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof ProtectedCartRoute
  '/wishlist': typeof ProtectedWishlistRoute
  '/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/login': typeof PublicAuthLoginRoute
  '/reset-password': typeof PublicAuthResetPasswordRoute
  '/signup': typeof PublicAuthSignupRoute
  '/verify-email': typeof PublicAuthVerifyEmailRoute
  '/products/$productId': typeof PublicProductsProductIdRoute
  '/categories': typeof PublicCategoriesIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/user/addresses': typeof ProtectedUserAddressesIndexRoute
  '/user/change-password': typeof ProtectedUserChangePasswordIndexRoute
  '/user/orders': typeof ProtectedUserOrdersIndexRoute
  '/user/profile': typeof ProtectedUserProfileIndexRoute
  '/user/sessions': typeof ProtectedUserSessionsIndexRoute
  '/products/deals': typeof PublicProductsDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected/cart': typeof ProtectedCartRoute
  '/_protected/wishlist': typeof ProtectedWishlistRoute
  '/_public/_auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/_public/_auth/signup': typeof PublicAuthSignupRoute
  '/_public/_auth/verify-email': typeof PublicAuthVerifyEmailRoute
  '/_public/products/$productId': typeof PublicProductsProductIdRoute
  '/_public/categories/': typeof PublicCategoriesIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_protected/user/addresses/': typeof ProtectedUserAddressesIndexRoute
  '/_protected/user/change-password/': typeof ProtectedUserChangePasswordIndexRoute
  '/_protected/user/orders/': typeof ProtectedUserOrdersIndexRoute
  '/_protected/user/profile/': typeof ProtectedUserProfileIndexRoute
  '/_protected/user/sessions/': typeof ProtectedUserSessionsIndexRoute
  '/_public/products/deals/': typeof PublicProductsDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/wishlist'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/products/$productId'
    | '/categories/'
    | '/products/'
    | '/user/addresses/'
    | '/user/change-password/'
    | '/user/orders/'
    | '/user/profile/'
    | '/user/sessions/'
    | '/products/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/wishlist'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/products/$productId'
    | '/categories'
    | '/products'
    | '/user/addresses'
    | '/user/change-password'
    | '/user/orders'
    | '/user/profile'
    | '/user/sessions'
    | '/products/deals'
  id:
    | '__root__'
    | '/'
    | '/_protected/cart'
    | '/_protected/wishlist'
    | '/_public/_auth/forgot-password'
    | '/_public/_auth/login'
    | '/_public/_auth/reset-password'
    | '/_public/_auth/signup'
    | '/_public/_auth/verify-email'
    | '/_public/products/$productId'
    | '/_public/categories/'
    | '/_public/products/'
    | '/_protected/user/addresses/'
    | '/_protected/user/change-password/'
    | '/_protected/user/orders/'
    | '/_protected/user/profile/'
    | '/_protected/user/sessions/'
    | '/_public/products/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedCartRoute: typeof ProtectedCartRoute
  ProtectedWishlistRoute: typeof ProtectedWishlistRoute
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute
  PublicAuthSignupRoute: typeof PublicAuthSignupRoute
  PublicAuthVerifyEmailRoute: typeof PublicAuthVerifyEmailRoute
  PublicProductsProductIdRoute: typeof PublicProductsProductIdRoute
  PublicCategoriesIndexRoute: typeof PublicCategoriesIndexRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
  ProtectedUserAddressesIndexRoute: typeof ProtectedUserAddressesIndexRoute
  ProtectedUserChangePasswordIndexRoute: typeof ProtectedUserChangePasswordIndexRoute
  ProtectedUserOrdersIndexRoute: typeof ProtectedUserOrdersIndexRoute
  ProtectedUserProfileIndexRoute: typeof ProtectedUserProfileIndexRoute
  ProtectedUserSessionsIndexRoute: typeof ProtectedUserSessionsIndexRoute
  PublicProductsDealsIndexRoute: typeof PublicProductsDealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/cart': {
      id: '/_protected/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ProtectedCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/wishlist': {
      id: '/_protected/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ProtectedWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/forgot-password': {
      id: '/_public/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/reset-password': {
      id: '/_public/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/signup': {
      id: '/_public/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/verify-email': {
      id: '/_public/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/categories/': {
      id: '/_public/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof PublicCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/products/$productId': {
      id: '/_public/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof PublicProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/addresses/': {
      id: '/_protected/user/addresses/'
      path: '/user/addresses'
      fullPath: '/user/addresses/'
      preLoaderRoute: typeof ProtectedUserAddressesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/change-password/': {
      id: '/_protected/user/change-password/'
      path: '/user/change-password'
      fullPath: '/user/change-password/'
      preLoaderRoute: typeof ProtectedUserChangePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/orders/': {
      id: '/_protected/user/orders/'
      path: '/user/orders'
      fullPath: '/user/orders/'
      preLoaderRoute: typeof ProtectedUserOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/profile/': {
      id: '/_protected/user/profile/'
      path: '/user/profile'
      fullPath: '/user/profile/'
      preLoaderRoute: typeof ProtectedUserProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/sessions/': {
      id: '/_protected/user/sessions/'
      path: '/user/sessions'
      fullPath: '/user/sessions/'
      preLoaderRoute: typeof ProtectedUserSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/products/deals/': {
      id: '/_public/products/deals/'
      path: '/products/deals'
      fullPath: '/products/deals/'
      preLoaderRoute: typeof PublicProductsDealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedCartRoute: ProtectedCartRoute,
  ProtectedWishlistRoute: ProtectedWishlistRoute,
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
  PublicAuthSignupRoute: PublicAuthSignupRoute,
  PublicAuthVerifyEmailRoute: PublicAuthVerifyEmailRoute,
  PublicProductsProductIdRoute: PublicProductsProductIdRoute,
  PublicCategoriesIndexRoute: PublicCategoriesIndexRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
  ProtectedUserAddressesIndexRoute: ProtectedUserAddressesIndexRoute,
  ProtectedUserChangePasswordIndexRoute: ProtectedUserChangePasswordIndexRoute,
  ProtectedUserOrdersIndexRoute: ProtectedUserOrdersIndexRoute,
  ProtectedUserProfileIndexRoute: ProtectedUserProfileIndexRoute,
  ProtectedUserSessionsIndexRoute: ProtectedUserSessionsIndexRoute,
  PublicProductsDealsIndexRoute: PublicProductsDealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
